---
name: demo

mimir:
  structuredConfig:
    blocks_storage:
      backend: filesystem

gateway:
  replicas: 0
query_frontend:
  replicas: 0
querier:
  replicas: 0
store_gateway:
  replicase: 0

ingester:
  replicas: 0

compactor:
  replicas: 0

alertmanager:
  enabled: false

ruler:
  enabled: false

minio:
  enabled: false

nginx:
  enabled: false
