---
name: stage

mimir-distributed:
  gateway:
    replicas: 0
  query_frontend:
    replicas: 0
  querier:
    replicas: 0

  ingester:
    replicas: 0

  alertmanager:
    enabled: false

  store_gateway:
    replicas: 0
    persistentVolume:
      enabled: false
    extraVolumes:
      - name: data
        emptyDir: {}
    extraVolumeMounts:
      - name: data
        mountPath: /blocks

  compactor:
    replicas: 0
    persistentVolume:
      enabled: false
    extraVolumes:
      - name: data
        emptyDir: {}
    extraVolumeMounts:
      - name: data
        mountPath: /blocks

  ruler:
    enabled: false

  minio:
    enabled: false

  nginx:
    enabled: false
